// Code generated by wsrpc-gen. DO NOT EDIT.
package service

import (
	"context"
	"fmt"
	"github.com/yingshulu/wsrpc/rpc"
)

type ChatRoomClient struct {
	h    rpc.ServiceHolder
	peer string
}

func NewChatRoomClient(h rpc.ServiceHolder, peer string) *ChatRoomClient {
	return &ChatRoomClient{h: h, peer: peer}
}

func (c *ChatRoomClient) SendMessage(ctx context.Context, req *ChatRequest, options ...rpc.Option) (*ChatResponse, error) {
	var res = &ChatResponse{}
	conn := c.h.GetConnByPeer(c.peer)
	if conn == nil {
		return nil, fmt.Errorf("connection %s not found", c.peer)
	}
	proxy := conn.GetProxy("service.ChatRoom.SendMessage")
	err := proxy.Call(ctx, req, res, options...)
	return res, err
}

func (c *ChatRoomClient) ReceiveMessage(ctx context.Context, req *ChatRequest, options ...rpc.Option) (*ChatResponse, error) {
	var res = &ChatResponse{}
	conn := c.h.GetConnByPeer(c.peer)
	if conn == nil {
		return nil, fmt.Errorf("connection %s not found", c.peer)
	}
	proxy := conn.GetProxy("service.ChatRoom.ReceiveMessage")
	err := proxy.Call(ctx, req, res, options...)
	return res, err
}

func RegisterChatRoomService(h rpc.ServiceHolder, service ChatRoom, options ...rpc.Option) {
	h.AddService("service.ChatRoom", service, options...)
}
